// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz-mf1tzz-n-B8FK70bpVZSKWhUv7DyEk',
    appId: '1:526601901570:web:da17c9596a96afaec8b91b',
    messagingSenderId: '526601901570',
    projectId: 'cw06-8fe6e',
    authDomain: 'cw06-8fe6e.firebaseapp.com',
    storageBucket: 'cw06-8fe6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp6XXWDNOAQMfs_FVq-vFJL-vExbWU66A',
    appId: '1:526601901570:android:83df0228c1811a7ac8b91b',
    messagingSenderId: '526601901570',
    projectId: 'cw06-8fe6e',
    storageBucket: 'cw06-8fe6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl77ChLeg8F9J1uluOTIrL3MBYOAWf0Kc',
    appId: '1:526601901570:ios:cc6417ef6a358270c8b91b',
    messagingSenderId: '526601901570',
    projectId: 'cw06-8fe6e',
    storageBucket: 'cw06-8fe6e.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl77ChLeg8F9J1uluOTIrL3MBYOAWf0Kc',
    appId: '1:526601901570:ios:cc6417ef6a358270c8b91b',
    messagingSenderId: '526601901570',
    projectId: 'cw06-8fe6e',
    storageBucket: 'cw06-8fe6e.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz-mf1tzz-n-B8FK70bpVZSKWhUv7DyEk',
    appId: '1:526601901570:web:3c0855a7414ae8ccc8b91b',
    messagingSenderId: '526601901570',
    projectId: 'cw06-8fe6e',
    authDomain: 'cw06-8fe6e.firebaseapp.com',
    storageBucket: 'cw06-8fe6e.firebasestorage.app',
  );
}
